@echo off
echo Killing all Node processes...
taskkill /F /IM node.exe 2>nul
echo Clearing all caches...
rd /s /q node_modules\.vite 2>nul
rd /s /q .vite 2>nul
rd /s /q dist 2>nul
echo Waiting for processes to terminate...
timeout /t 2 >nul
echo Starting fresh dev server...
npm run dev
pause 