
import React from 'react';
import { motion } from 'framer-motion';
import { useAppContext } from '@/contexts/AppContext';

const DisclaimerView = () => {
  const { language, translations } = useAppContext();
  const t = translations[language];
  const currentDate = new Date().toLocaleDateString(language === 'de' ? 'de-DE' : 'en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="prose dark:prose-invert max-w-none p-6 bg-background/50 dark:bg-slate-800/50 rounded-lg shadow-lg"
    >
      <div className="mb-8 p-4 border-l-4 border-yellow-500 bg-yellow-50 dark:bg-yellow-900/30 rounded-md">
        <h3 className="font-bold text-yellow-700 dark:text-yellow-300">{language === 'de' ? 'WICHTIGER HINWEIS' : 'IMPORTANT NOTICE'}</h3>
        <p className="text-sm text-yellow-600 dark:text-yellow-200">
          {t.legalProfessionalDisclaimer}
        </p>
      </div>

      <h1 className="text-3xl font-bold gradient-text mb-6">{t.disclaimerTitle}</h1>
      <p className="text-sm text-muted-foreground mb-6">
        {t.lastUpdated.replace('{date}', currentDate)}
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-3">1. {language === 'de' ? 'Keine Finanz-, Anlage- oder Steuerberatung' : 'No Financial, Investment, or Tax Advice'}</h2>
      <p>{language === 'de' ? 'Die von PulseManager ("die Anwendung"), entwickelt von Kuddel Tech, bereitgestellten Informationen und Werkzeuge dienen ausschließlich allgemeinen Informations- und Bildungszwecken. Alle Informationen und Werkzeuge in der Anwendung werden nach bestem Wissen und Gewissen bereitgestellt; wir übernehmen jedoch keine ausdrückliche oder stillschweigende Gewähr für die Richtigkeit, Angemessenheit, Gültigkeit, Zuverlässigkeit, Verfügbarkeit oder Vollständigkeit von Informationen oder Werkzeugen in der Anwendung.' : 'The information and tools provided by PulseManager ("the Application"), developed by Kuddel Tech, are for general informational and educational purposes only. All information and tools on the Application are provided in good faith; however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information or tools on the Application.'}</p>
      <p>{language === 'de' ? 'Unter keinen Umständen haften Kuddel Tech oder seine Entwickler Ihnen gegenüber für Verluste oder Schäden jeglicher Art, die durch die Nutzung der Anwendung oder das Vertrauen auf Informationen oder Werkzeuge in der Anwendung entstehen. Ihre Nutzung der Anwendung und Ihr Vertrauen auf Informationen oder Werkzeuge in der Anwendung erfolgen ausschließlich auf Ihr eigenes Risiko.' : 'Under no circumstance shall Kuddel Tech or its developers have any liability to you for any loss or damage of any kind incurred as a result of the use of the Application or reliance on any information or tools provided on the Application. Your use of the Application and your reliance on any information or tools on the Application is solely at your own risk.'}</p>
      <p><strong>{language === 'de' ? 'DIE ANWENDUNG KANN UND ENTHÄLT KEINE FINANZ-, ANLAGE- ODER STEUERBERATUNG.' : 'THE APPLICATION CANNOT AND DOES NOT CONTAIN FINANCIAL, INVESTMENT, OR TAX ADVICE.'}</strong> {language === 'de' ? 'Die finanz-, anlage- und steuerbezogenen Informationen und Werkzeuge werden ausschließlich zu allgemeinen Informations- und Bildungszwecken bereitgestellt und sind kein Ersatz für professionelle Beratung. Dementsprechend empfehlen wir Ihnen dringend, vor Maßnahmen auf der Grundlage solcher Informationen oder Werkzeuge qualifizierte Fachleute (z. B. einen lizenzierten Finanzberater, Anlageberater oder Steuerberater) zu konsultieren. Wir bieten keinerlei Finanz-, Anlage- oder Steuerberatung an. DIE NUTZUNG ODER DAS VERTRAUEN AUF INFORMATIONEN ODER WERKZEUGE IN DIESER ANWENDUNG ERFOLGT AUSSCHLIESSLICH AUF IHR EIGENES RISIKO.' : 'The financial, investment, and tax-related information and tools are provided for general informational and educational purposes only and are not a substitute for professional advice. Accordingly, before taking any actions based upon such information or tools, we strongly encourage you to consult with appropriate qualified professionals (e.g., a licensed financial advisor, investment advisor, or tax professional). We do not provide any kind of financial, investment, or tax advice. THE USE OR RELIANCE OF ANY INFORMATION OR TOOLS CONTAINED ON THIS APPLICATION IS SOLELY AT YOUR OWN RISK.'}</p>

      <h2 className="text-xl font-semibold mt-6 mb-3">2. {language === 'de' ? 'Anlagerisiken und Volatilität' : 'Investment Risks and Volatility'}</h2>
      <p>{language === 'de' ? 'Investitionen in Kryptowährungen und verwandte digitale Vermögenswerte sind hochspekulativ und bergen ein erhebliches Risiko erheblicher Verluste. Der Wert von Kryptowährungen kann extrem volatil sein und innerhalb kurzer Zeit dramatisch schwanken. Sie sollten sich bewusst sein, dass Sie Ihr gesamtes investiertes Kapital verlieren könnten. Sie sollten kein Geld investieren, dessen Verlust Sie sich nicht leisten können. Bevor Sie sich für den Handel oder die Investition in Kryptowährungen entscheiden, sollten Sie Ihre Anlageziele, Ihren Erfahrungsstand und Ihre Risikobereitschaft sorgfältig prüfen und einen unabhängigen Finanzberater konsultieren.' : 'Investing in cryptocurrencies and related digital assets is highly speculative and carries a significant risk of substantial loss. The value of cryptocurrencies can be extremely volatile and can fluctuate dramatically in a short period. You should be aware that you could lose all of your invested capital. You should not invest money that you cannot afford to lose. Before deciding to trade or invest in cryptocurrencies, you should carefully consider your investment objectives, level of experience, risk appetite, and consult with an independent financial advisor.'}</p>

      <h2 className="text-xl font-semibold mt-6 mb-3">3. {language === 'de' ? 'Links, Dienste und eingebettete Inhalte von Drittanbietern' : 'Third-Party Links, Services, and Embedded Content'}</h2>
      <p>{language === 'de' ? 'Die Anwendung kann Links zu anderen Websites oder Inhalten enthalten (oder Sie können über die Anwendung dorthin weitergeleitet werden), die Dritten gehören oder von diesen stammen, oder eingebettete Schnittstellen zu Diensten Dritter (z. B. PulseX, Matcha.xyz, Portal Bridge, DexScreener). Solche externen Links und eingebetteten Dienste werden von uns nicht auf Richtigkeit, Angemessenheit, Gültigkeit, Zuverlässigkeit, Verfügbarkeit oder Vollständigkeit untersucht, überwacht oder geprüft.' : 'The Application may contain (or you may be sent through the Application) links to other websites or content belonging to or originating from third parties, or embedded interfaces to third-party services (e.g., PulseX, Matcha.xyz, Portal Bridge, DexScreener). Such external links and embedded services are not investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability, or completeness by us.'}</p>
      <p>{language === 'de' ? 'Wir übernehmen keine Gewähr, Billigung, Garantie oder Verantwortung für die Richtigkeit oder Zuverlässigkeit von Informationen, die von Websites oder Diensten Dritter angeboten werden, die über die Anwendung verlinkt sind, oder für Websites oder Funktionen, die in Bannern oder anderer Werbung verlinkt sind, noch für Transaktionen, die Sie mit diesen Dritten durchführen. Wir sind nicht Partei oder in irgendeiner Weise verantwortlich für die Überwachung von Transaktionen zwischen Ihnen und Drittanbietern von Produkten oder Dienstleistungen. Sie interagieren mit diesen Diensten Dritter auf eigenes Risiko.' : 'We do not warrant, endorse, guarantee, or assume responsibility for the accuracy or reliability of any information offered by third-party websites or services linked through the Application or any website or feature linked in any banner or other advertising, nor for any transactions you conduct with these third parties. We will not be a party to or in any way be responsible for monitoring any transaction between you and third-party providers of products or services. You interact with these third-party services at your own risk.'}</p>

      <h2 className="text-xl font-semibold mt-6 mb-3">4. {language === 'de' ? 'Richtigkeit und Aktualität der Informationen' : 'Accuracy and Timeliness of Information'}</h2>
      <p>{language === 'de' ? 'Obwohl wir uns bemühen, genaue und aktuelle Informationen und Berechnungen (z. B. Token-Preise, ROI, steuerbezogene Daten) bereitzustellen, ist der Kryptowährungsmarkt schnelllebig und ständig im Wandel. Von der Anwendung bereitgestellte Informationen, einschließlich, aber nicht beschränkt auf Token-Preise, Marktdaten, ROI-Berechnungen und steuerbezogene Informationen, sind möglicherweise nicht immer aktuell, genau oder vollständig. Daten können von APIs Dritter stammen und unterliegen deren Verfügbarkeit und Genauigkeit. Sie sollten alle Informationen unabhängig überprüfen, bevor Sie finanzielle Entscheidungen treffen.' : 'While we strive to provide accurate and up-to-date information and calculations (e.g., token prices, ROI, tax-related data), the cryptocurrency market is fast-paced and constantly changing. Information provided by the Application, including but not limited to token prices, market data, ROI calculations, and tax-related information, may not always be current, accurate, or complete. Data may be sourced from third-party APIs and is subject to their availability and accuracy. You should independently verify any information before making any financial decisions.'}</p>
      <p>{language === 'de' ? 'Steuerbezogene Informationen und Werkzeuge, die von der Anwendung bereitgestellt werden, dienen nur zu Informationszwecken und sind kein Ersatz für professionelle Steuerberatung. Steuergesetze variieren je nach Gerichtsbarkeit und können sich ändern. Die Anwendung garantiert nicht die Einhaltung aller Steuervorschriften. Konsultieren Sie einen qualifizierten Steuerberater für eine auf Ihre spezifische Situation zugeschnittene Beratung.' : 'Tax-related information and tools provided by the Application are for informational purposes only and are not a substitute for professional tax advice. Tax laws vary by jurisdiction and are subject to change. The Application does not guarantee compliance with all tax regulations. Consult with a qualified tax professional for advice tailored to your specific situation.'}</p>

      <h2 className="text-xl font-semibold mt-6 mb-3">5. {language === 'de' ? 'Softwarerisiken und Sicherheit' : 'Software Risks and Security'}</h2>
      <p>{language === 'de' ? 'Sie erkennen an, dass Software niemals vollständig frei von Fehlern, Schwachstellen und Auslassungen ist. Die Nutzung der Anwendung erfolgt auf eigenes Risiko. Wir sind nicht verantwortlich für Verluste oder Schäden, die durch Software-Schwachstellen, Fehler oder durch Ihre missbräuchliche oder falsche Verwendung der Anwendung entstehen.' : 'You acknowledge that software is never entirely free from bugs, errors, vulnerabilities, and omissions. The use of the Application is at your own risk. We are not responsible for any losses or damages resulting from software vulnerabilities, bugs, errors, or from your misuse or misunderstanding of the Application.'}</p>
      <p>{language === 'de' ? 'Sie sind allein verantwortlich für die Sicherheit Ihrer Kryptowährungs-Wallet(s), privaten Schlüssel, Seed-Phrasen und Passwörter. PulseManager wird Sie NIEMALS nach Ihren privaten Schlüsseln oder Seed-Phrasen fragen. Seien Sie wachsam gegenüber Phishing-Versuchen und Betrügereien. Teilen Sie Ihre sensiblen Wallet-Informationen mit niemandem.' : 'You are solely responsible for the security of your cryptocurrency wallet(s), private keys, seed phrases, and passwords. PulseManager will NEVER ask for your private keys or seed phrases. Be vigilant against phishing attempts and scams. Do not share your sensitive wallet information with anyone.'}</p>

      <h2 className="text-xl font-semibold mt-6 mb-3">6. {language === 'de' ? 'Keine Billigung' : 'No Endorsement'}</h2>
      <p>{language === 'de' ? 'Die Nennung einer bestimmten Kryptowährung, eines Tokens, eines Projekts, einer Dienstleistung oder eines Unternehmens innerhalb der Anwendung stellt keine Billigung oder Empfehlung durch Kuddel Tech dar. Alle Informationen werden nur zu Informationszwecken bereitgestellt.' : 'Reference to any specific cryptocurrency, token, project, service, or company within the Application does not constitute an endorsement or recommendation by Kuddel Tech. All information is provided for informational purposes only.'}</p>
      
      <h2 className="text-xl font-semibold mt-6 mb-3">7. {language === 'de' ? 'Annahme dieses Haftungsausschlusses' : 'Acceptance of this Disclaimer'}</h2>
      <p>{language === 'de' ? 'Durch die Nutzung der Anwendung erklären Sie Ihre Annahme dieses Haftungsausschlusses und stimmen zu, an dessen Bedingungen gebunden zu sein. Wenn Sie diesem Haftungsausschluss nicht zustimmen, verwenden Sie unsere Anwendung bitte nicht. Ihre fortgesetzte Nutzung der Anwendung nach der Veröffentlichung von Änderungen an diesem Haftungsausschluss gilt als Ihre Annahme dieser Änderungen.' : 'By using the Application, you signify your acceptance of this Disclaimer and agree to be bound by its terms. If you do not agree to this Disclaimer, please do not use our Application. Your continued use of the Application following the posting of changes to this Disclaimer will be deemed your acceptance of those changes.'}</p>
      
      <p className="mt-8 text-sm text-red-500 dark:text-red-400">
        <strong>{t.legalProfessionalDisclaimer}</strong>
      </p>
    </motion.div>
  );
};

export default DisclaimerView;
